version: "3"
services:
  directus:
    image: directus/directus:10.8.2
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      KEY: "058109c6723-fe0936d8-cb76341a-7402764dec"
      SECRET: "15809c6723-fe0936d8-1379712-7274324fea"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: true
      CORS_ENABLED: 'true'
      CORS_ORIGIN: 'http://localhost:3000'
      CORS_METHODS: 'GET,POST,PATCH,DELETE,OPTIONS'
      CORS_ALLOWED_HEADERS: 'Content-Type,Authorization'
      CORS_EXPOSED_HEADERS: 'Content-Range'
      CORS_CREDENTIALS: 'true'
